"""
TodoService implementing business logic for task management.
This service uses dependency injection to work with any TaskRepository implementation.
"""

from typing import List, Optional
from src.core.entities.task import Task, TaskStatus
from src.core.repositories.task_repository import TaskRepository
from src.core.utils.validation import validate_task_title


class TodoService:
    """Service class that handles business logic for task management"""

    def __init__(self, task_repository: TaskRepository):
        self.task_repository = task_repository

    def add_task(self, title: str) -> Task:
        """Creates a new task with the provided title and returns it"""
        # Validate the task title
        is_valid, error_msg = validate_task_title(title)
        if not is_valid:
            raise ValueError(error_msg)

        # Create a new task (ID will be auto-generated by repository)
        task = Task(id=0, title=title.strip())  # ID will be set by repository
        return self.task_repository.create(task)

    def list_tasks(self) -> List[Task]:
        """Returns all tasks"""
        return self.task_repository.get_all()

    def get_task(self, task_id: int) -> Optional[Task]:
        """Returns task with given ID or None if not found"""
        return self.task_repository.get_by_id(task_id)

    def update_task(self, task_id: int, title: str) -> bool:
        """Updates the title of an existing task, returns True if successful"""
        # Validate the task title
        is_valid, error_msg = validate_task_title(title)
        if not is_valid:
            raise ValueError(error_msg)

        # Get the existing task
        existing_task = self.task_repository.get_by_id(task_id)
        if existing_task is None:
            return False

        # Update the task
        updated_task = Task(id=task_id, title=title.strip(), status=existing_task.status)
        result = self.task_repository.update(task_id, updated_task)
        return result is not None

    def mark_complete(self, task_id: int) -> bool:
        """Marks a task as completed, returns True if successful"""
        # Get the existing task
        existing_task = self.task_repository.get_by_id(task_id)
        if existing_task is None:
            return False

        # Update the task status to completed
        updated_task = Task(id=task_id, title=existing_task.title, status="completed")
        result = self.task_repository.update(task_id, updated_task)
        return result is not None

    def delete_task(self, task_id: int) -> bool:
        """Removes a task from the system, returns True if successful"""
        return self.task_repository.delete(task_id)

    def validate_task(self, title: str) -> bool:
        """Validates task data before creation/updating"""
        is_valid, _ = validate_task_title(title)
        return is_valid